name: point_pillar_where2comm
root_dir: '/mnt/1c19fbb2-4609-4579-9be5-7e8b872cfcd7/research/data/opv2v/train'
validate_dir: '/mnt/1c19fbb2-4609-4579-9be5-7e8b872cfcd7/research/data/opv2v/validate'


wild_setting:
  seed: 20
  async: False
  async_mode: 'sim'
  async_overhead: 100
  loc_err: False
  xyz_std: 0.2
  ryp_std: 0.2
  data_size: 1.06  # Mb
  transmission_speed: 27  # Mbps
  backbone_delay: 10  # ms

yaml_parser: 'load_point_pillar_params'
train_params:
  batch_size: &batch_size 1
  epoches: &epoches 50
  eval_freq: 1
  save_freq: 1
  max_cav: &max_cav 5

fusion:
  core_method: 'IntermediateFusionDataset'  # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args: [ ]

# Preprocess-related
preprocess:
  # Options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [ 0.25, 0.25, 4 ]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000

    #camera 参数
    bgr2rgb: true
    resize_x: &image_width 512
    resize_y: &image_height 512
    mean: [ 0.485, 0.456, 0.406 ]
    std: [ 0.229, 0.224, 0.225 ]
  # LiDAR range for each individual CAV
  cav_lidar_range: &cav_lidar [ -64, -64, -3, 64, 64, 1 ]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]
  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]
  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# Anchor box related
postprocess:
  core_method: 'VoxelPostprocessor'  # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [ 0, 90 ]
    num: &achor_num 2
    feature_stride: 4
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: 'hwl'  # hwl or lwh
  max_num: 100  # Maximum number of objects in a single frame. Use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# Model related
model:
  core_method: point_pillar_where2comm
  args:
#    target: &target 'dynamic' # dynamic, static or both
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    head_dim: 256
    max_cav: *max_cav
    compression: 0  # Compression rate
    backbone_fix: False
    # 图像处理
    encoder:
      num_layers: 34
      pretrained: true
      image_width: *image_width
      image_height: *image_height
      id_pick: [ 1 ,2, 3 ]
    fax:
      dim: [ 128, 128, 128 ] # b, d, h w from resenet -> b 256 h w
      middle: [ 2, 2, 2 ] # middle conv
      bev_embedding:
        sigma: 1.0
        bev_height: 256
        bev_width: 256
        h_meters: 128
        w_meters: 128
        offset: 0.0
        upsample_scales: [ 2, 4, 8 ]

      cross_view: #cross_view attention
        image_height: *image_height
        image_width: *image_width
        no_image_features: False
        skip: True
        heads: [ 4, 4, 4 ]
        dim_head: [ 32, 32, 32 ]
        qkv_bias: True

      cross_view_swap:
        rel_pos_emb: False
        q_win_size: [ [ 16, 16 ], [ 16, 16 ], [ 32, 32 ] ]#滑窗的大小
        feat_win_size: [ [ 8, 8 ], [ 8, 8 ], [ 16, 16 ] ] #滑窗的大小
        bev_embedding_flag: [ true, false, false ]

      self_attn:
        dim_head: 32
        dropout: 0.1
        window_size: 32 #滑窗的大小
    decoder:
      input_dim: 128
      num_layer: 3
      num_ch_dec: &decoder_block [ 32, 64 ,128 ]
    SE:
      input_dim: 256
    

    pillar_vfe:
      use_norm: True
      with_distance: False
      use_absolute_xyz: True
      num_filters: [ 64 ]
    point_pillar_scatter:
      num_features: 64
    base_bev_backbone:
      layer_nums: &layer_nums [ 3, 5, 8 ]
      layer_strides: [ 2, 2, 2 ]
      num_filters: &num_filters [ 64, 128, 256 ]
      upsample_strides: [ 1, 2, 4 ]
      num_upsample_filter: [ 128, 128, 128 ]
    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 2 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384  # 128 * 3
    # v2vfusion:
    #   voxel_size: *voxel_size
    #   downsample_rate: 4
    #   num_iteration: 2
    #   in_channels: 256
    #   gru_flag: true
    #   agg_operator: "avg" # max or avg
    #   conv_gru:
    #     H: 128
    #     W: 128
    #     num_layers: 1
    #     kernel_size: [[3,3]]
    where2comm_fusion:
       fully: False
       voxel_size: *voxel_size
       downsample_rate: 4
       in_channels: 256
       multi_scale: False
       layer_nums: *layer_nums
       num_filters: *num_filters
       communication:
         round: 1
         threshold: 0.01
         gaussian_smooth:
           k_size: 5
           c_sigma: 1.0
    channel_block:
      input_dim: 10
      out_dim: 5


#    fax_fusion:
#      input_dim: 256
#      mlp_dim: 256
#      agent_size: *max_cav
#      window_size: 4
#      dim_head: 32
#      drop_out: 0.1
#      depth: 3
#      mask: true

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 2e-4
  args:
    eps: 1e-10
    weight_decay: 1e-2

lr_scheduler:
  core_method: cosineannealwarm # step, multistep, exponential and cosineannealwarm support
  epoches: *epoches
  warmup_lr: 2e-5
  warmup_epoches: 10
  lr_min: 5e-6